// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SDAE.Data
{
    public partial class ClientInfo
    {
        public long Id { get; set; }
        public string Info { get; set; }
        public DateTime AddedDate { get; set; }
    }
}