// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SDAE.Data
{
    public partial class LoginStatusTypes
    {
        public LoginStatusTypes()
        {
            UserLogs = new HashSet<UserLogs>();
        }

        public int LoginStatusTypeId { get; set; }
        public string Name { get; set; }

        public virtual ICollection<UserLogs> UserLogs { get; set; }
    }
}