// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SDAE.Data
{
    public partial class StatusTypes
    {
        public StatusTypes()
        {
            Sdaekeywords = new HashSet<Sdaekeywords>();
            TwitterDetails = new HashSet<TwitterDetails>();
        }

        public byte StatusTypeId { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Sdaekeywords> Sdaekeywords { get; set; }
        public virtual ICollection<TwitterDetails> TwitterDetails { get; set; }
    }
}