// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SDAE.Data
{
    public partial class UserLogs
    {
        public long UserLogId { get; set; }
        public string UserName { get; set; }
        public string UserId { get; set; }
        public string ClientIp { get; set; }
        public DateTime LogonTime { get; set; }
        public DateTime? LogoutTime { get; set; }
        public Guid SessionId { get; set; }
        public string DeviceModel { get; set; }
        public string DeviceToken { get; set; }
        public short? LoginDeviceTypeId { get; set; }
        public int? LoginStatusTypeId { get; set; }

        public virtual LoginStatusTypes LoginStatusType { get; set; }
    }
}